/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.mosolov.gku;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

@SpringBootApplication
public class GkuTest extends SpringBootServletInitializer{

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(GkuTest.class);
    }

    public static void main(String[] args) {

        SpringApplication.run(GkuTest.class, args);
    }
}
